### ISSUE TITLE
Assemble 6x kits + 1x spare

### ISSUE THREAD

**Issue by xfxf** [xfxf/lca2017-av#16]
https://docs.google.com/spreadsheets/d/1uc_QICAHcZtQpQxt8bpTy2hKk7BN11h375hLQG0wcoA/edit?disco=AAAAA1WOp8Y&usp=comment_email_document

**Comment by mithro** [comment]
@xfxf Can you make this a high priority to get updated with info about camera and scalers?

**Comment by xfxf** [comment]
Done.  Notes:

* Opsis's required currently: Absolute minimum 13,, ideally 16.  11 for main rooms (including 2 for Plenary, each podium), 1 for speakers room, 1 extra for additional camera in Plenary (optional), 2 spares in AV room.

* Opsis requirements could be reduced by using a desktop PC (I have a spare) in one of the rooms and using Blackmagic PCIe ingest (I'd prefer only doing it in the main room though), using Carl's cameras with his ethernet dongle, and dropping the second camera in Plenary (reduces by up to 4).

* Scalers are currently used for HV20/HV30 LCA cameras, as they don't work directly on the Opsis.  If they do, we don't need the scalers.

* Unless the issues we identified with connecting to the venues Blackmagic gear is resolved we will need 2 *additional* scalers for each lecturn podium in Plenary.  I only have 4.  The venue has some we can borrow however.

* I need to confirm with Steve what network switches are being supplied.  We need a big one for our A/V room (at least 12 ports), with small switch per room for the network in the room.

* We only have 5x VGA to HDMI converters (I ordered more, they never arrived).  I have a proper VGA to HDMI scaler (which we'll put in plenary), will need something for speakers room.

**Comment by mithro** [comment]
We can't depend on Carl's cameras doing Ethernet.

**Comment by xfxf** [comment]
It's an option to investigate if we're short on Opsis's.  I also don't want to use the spare desktop, or reduce Opsis usage elsewhere.

**Comment by mithro** [comment]
It's not an option. We don't have the bandwidth to make it work. Maybe in the future.
