### ISSUE TITLE
Shopping List

### ISSUE THREAD

**Issue by xfxf** [xfxf/lca2017-av#18]
Add to this if we need to locate/buy things before LCA.

**Comment by xfxf** [comment]
* Archer C7 access point
* Additional labels

**Comment by joeladdison** [comment]
* Full size DP to HDMI

**Comment by joeladdison** [comment]
* 5V power supply for Carl's crappy cam

**Comment by mithro** [comment]
Did you get the Full size DP to HDMI?

**Comment by xfxf** [comment]
No.  Everything is insanely expensive here in Hobart, and the place I found
them at only had 4 anyway -  it's not a requirement.  It's too late to be
buying optional things.

**Comment by xfxf** [comment]
Actually, scratch that, MSY had stock of the cheaper dongles (not the
cables).  But right now I'm going to argue against me spending 1h30m taking
a trip there for an optional component given everything else we need to be
working on - we're a couple of days out.
