### ISSUE TITLE
Figure out what to do about cases + power supplies for extra Opsis boards

### ISSUE THREAD

**Issue by mithro** [xfxf/lca2017-av#21]
Currently  https://docs.google.com/spreadsheets/d/1uc_QICAHcZtQpQxt8bpTy2hKk7BN11h375hLQG0wcoA/edit#gid=441420403 says we need 17 opsis boards.

I think we have ~10 with cases + power supplies....

**Comment by xfxf** [comment]
@mithro we have 10 in cases, 2 extra cases, and that's it.  Can you propose what you want done?  Buying cases + PSU's from a local computer retailer in Hobart isn't going to be cheap... would you be OK running the extra Opsis's without a case?

**Comment by xfxf** [comment]
PSU's we might be OK with, I have extras and there's a bunch of LCA PSU's.  I'll check now...

**Comment by xfxf** [comment]
I can count 14 of them right now around the place + in bags, there's 4x Netgear switches we're not using with compatible power supplies, I'm probably missing a few too (there are LCA ones somewhere, possibly in the van, will check), plus do you have any?  We probably have enough PSU's.

**Comment by mithro** [comment]
I'm too tired to figure out the solution right now but other random thoughts....

I would rather not run Opsis boards in public locations without cases. Probably okay if they are hidden *inside* podiums.

**Comment by xfxf** [comment]
I agree, I just don't see us getting hold of small cases in Hobart in the next day.

**Comment by xfxf** [comment]
I can count 24x USB cables.  We need 5x for the Yamaha soundcards, ~17 for the Opsis's, and a few spares.  Assuming a few of us also have some spares, think OK here.

**Comment by mithro** [comment]
I brought redmere cables + usb cables for my Opsis boards - just no power supplies or cases...

**Comment by xfxf** [comment]
I don't think buying ~6 tiny cases is an option - we have one business day before the conference opens.  It'd need to be ordered from interstate.

**Comment by mithro** [comment]
We might be able to mount them in the cardboard boxes in some way

**Comment by xfxf** [comment]
Closing - nothing we can action here before deploy time.

**Comment by mithro** [comment]
This problem still needs to be solved. Closing it doesn't make it go away.

**Comment by xfxf** [comment]
I disagree with re-opening this; this is self evident during deploy time (there's nothing we can do between now and deploy time), and having many 'in progress' tasks in our Kanban board makes project management useless.  But I'll leave it open but in the 'done' column.
