### ISSUE TITLE
Import the schedule from LCA into the streaming system

### ISSUE THREAD

**Issue by mithro** [xfxf/lca2017-av#22]
LCA is using Symposium this year, which isn't zookeeper.

https://github.com/timvideos/streaming-system/tree/master/website
`streaming-system/website/frontend/xxx2internal.py`

**Comment by micolous** [comment]
Wrote https://github.com/timvideos/streaming-system/blob/master/website/symposion2internal.py

@joeladdison now has a `config.private.json` which can be used with it to build a schedule.
