### ISSUE TITLE
Youtube Streaming (test, ready, commit scripts to video-scripts repo)

### ISSUE THREAD

**Issue by mithro** [xfxf/lca2017-av#23]

**Comment by mithro** [comment]
https://github.com/timvideos/streaming-system/commit/15d4a3e82d8afc2e956901c68f438f846e8929f8

**Comment by micolous** [comment]
There's also some scripts for this in https://github.com/xfxf/video-scripts/tree/master/michael

- youtube-live.sh: voctomix youtube streaming
- youtube-dvswitch.sh: dvsitch youtube streaming
- youtube-test.sh: colour bar test

**Comment by xfxf** [comment]
@joeladdison can I verify everything we used this year has been committed up somewhere (and if so, links?)

**Comment by joeladdison** [comment]
@xfxf The client scripts are in ansible now, and include options for both vaapi and normal - https://anonscm.debian.org/cgit/debconf-video/ansible.git/tree/roles/voctomix/templates/videoteam-stream.j2

I'll get the youtube test script (https://gist.github.com/joeladdison/6e9fe495eab7856a44d9f405ed493af8) added to the streaming repo later as well, so we have both available for use.

All of the changes that I made to the streaming site have already been committed.
