### ISSUE TITLE
Ansible setup on AV server for imaging laptops

### ISSUE THREAD

**Issue by xfxf** [xfxf/lca2017-av#4]
End goal is to PXE boot + install Ubuntu 16.04 LTS (with all updates).

Should easily be able to associate a new laptop to a particular room role.

Don't erase the existing imaging we have working on the server (so we have a backup option).

Should include:
 * All 16.04 LTS updates (latest gstreamer updates)
 * Latest voctomix
 * Ability to run all required voctomix components (1x remote laptop w/ HDMI2USB, local laptop w/HDMI2USB+ALSA device or Blackmagic, cut script, video capture script)
 * Support for blackmagic cards (drive installed)
 * HDMI2USB flashing tools (so @mithro can ssh in and reflash Opsis's if required)
 * Encoding tools + configured against veyepar,'s db so can be used as encode stations

Should include @joeladdison's monitoring software too later in the week once this is ready.

**Comment by CarlFK** [comment]
(04:29:55 PM) videoteam-r3grab: CarlFK, Make sure the following are installed - xchat-gnome, bash-completion, vim-gnome, mplayer, vlc, ffmpeg/avconv, fxload, tmux, git

**Comment by stefanor** [comment]
@mithro:

> xchat-gnome

We have hexchat

> * bash-completion
> * vim-gnome
> * mplayer
> * vlc
> * ffmpeg/avconv
> * fxload
> * git

done

**Comment by mithro** [comment]
Can you make sure that modem-manager is *NOT* installed.

Remove xscreensaver too?

**Comment by xfxf** [comment]
hdmi2usbd (github.com/deeprave/hdmi2usbd).  @deeprave will make a release

**Comment by xfxf** [comment]
* Icon on desktop for VoctoGUI (so people can quit + restart it)
* Display cut file on screen
* Remove #linux.conf.au from channels auto-joined in IRC client (don't want distractions, should be AV focussed only - #lca-av and the channel for the room is sufficient)

**Comment by mithro** [comment]
Things which are currently missing;

 * vlc
 * mplayer
 * totem
 * gstreamer1.0-plugins-*
 * flterm

**Comment by stefanor** [comment]
@xfxf: Done.

@mithro: That should all be on *all* the boxes now.
