### ISSUE TITLE
Determine/fix output refresh rate for HDMI2USB for Panasonic projectors

### ISSUE THREAD

**Issue by xfxf** [xfxf/lca2017-av#8]
Wrest Point uses Panasonic 16:10 (native res 1920x1200) projectors with a Panasonic ET-YFB200 box which takes various inputs (including HDMI).

This works fine with the Opsis at 720p50h, but 720p60 has significant chopped off pixels on the left.

AV guy tried to adjust settings  try a second YFB200 box, nothing fixed it.  I have observed the same ~2 years ago on early HDMI2USB firmware with an Atlys.

![128px test pattern](https://cloud.githubusercontent.com/assets/138684/21757477/7f4122b2-d683-11e6-8766-966b8441eed1.png)

Do we fix this, or do we run 720p50 as the output resolution @mithro?

**Comment by mithro** [comment]
Did you dump the EDID info of the projector?

**Comment by xfxf** [comment]
@mithro no, I did not dump EDID info.  Can you advise on how we should tackle this (i.e. can we run 50hz as the output while allowing 50/60hz for the input, or something else?)
